# Generated by Django 4.2.7 on 2026-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('credentials', models.JSONField()),
                ('status', models.CharField(default='Disconnected', max_length=20)),
                ('last_tested', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
